version: '3'
services:
    router:
        image: ytmusicquiz-proxy
        build: proxy
        environment:
            DASHBOARD_HOST: dashboard
            BACKEND_HOST: backend
            STATIC_HOST: static
        ports:
            - '8080:80'

    dashboard:
        image: ytmusicquiz-dashboard
        build: ../ytmusicquiz-dashboard/

    backend:
        image: ytmusicquiz
        build: ../ytmusicquiz/
        environment:
            REDIS_HOST: redis

    static:
        image: ytmusicquiz-static
