version: '3'
services:
    router:
        image: ${DOCKER_REGISTRY}/ytmusicquiz-proxy
        build: proxy

    dashboard:
        image: ${DOCKER_REGISTRY}/ytmusicquiz-dashboard
        build: ../ytmusicquiz-dashboard/

    backend:
        image: ${DOCKER_REGISTRY}/ytmusicquiz
        build: ../ytmusicquiz/

    static:
        image: ${DOCKER_REGISTRY}/ytmusicquiz-static
        build:
            context: ../ytmusicquiz/
            dockerfile: Dockerfile-static

    redis:
        image: redis